# Generated by Django 2.0.6 on 2018-06-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Activity Type Code')),
                ('desc', models.CharField(max_length=60, verbose_name='Activity Type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCatalog',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Order Catalog Code')),
                ('long_desc', models.CharField(max_length=60, verbose_name='Long Description')),
                ('short_desc', models.CharField(max_length=40, verbose_name='Short Description')),
                ('status', models.CharField(default='New', max_length=20, verbose_name='Status')),
                ('activity_type', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='datasheet.ActivityType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Order Catagory Code')),
                ('desc', models.CharField(max_length=60, verbose_name='Order Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Order Type Code')),
                ('desc', models.CharField(max_length=60, verbose_name='Order Type')),
                ('order_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasheet.OrderCategory')),
            ],
        ),
        migrations.AddField(
            model_name='ordercatalog',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasheet.OrderType'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasheet.OrderType'),
        ),
    ]
