# Generated by Django 2.0.6 on 2018-06-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercatalog',
            name='status',
            field=models.CharField(default='New', max_length=100, verbose_name='Status'),
        ),
    ]
